version: '2'
services:
  db-mongodb:
    image: mongo:3.6
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE

    volumes:
        - db-mongodb.mdb:/data/db

  app-rabbit:
    image: rabbitmq:latest
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE

  app-girder-worker:
    image: openchemistry/girder_worker:mdb
#    build:
#      context: ../../
#      dockerfile: devops/docker/girder_worker/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - app-rabbit
      - app-girder
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@app-rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@app-rabbit/
    depends_on:
      - app-rabbit

  app-girder:
    image: openchemistry/girder:mdbv0.0.1
#    build:
#      context: ../../
#      dockerfile: devops/docker/girder/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    retain_ip: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE

    command: -d mongodb://db-mongodb:27017/girder
    ports:
          - 8081:8080
    volumes:
      - app-localassetstore.mdb:/assetstore
      - app-curatedassetstore.mdb:/curatedassetstore
    links:
      - db-mongodb
      - app-rabbit
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@app-rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@app-rabbit/
    depends_on:
      - db-mongodb

  web-nginx:
    image: openchemistry/nginx:mdb-v0.0.3
#    build:
#      context: ../../
#      dockerfile: devops/docker/nginx/Dockerfile
    labels:
      io.rancher.container.pull_image: always
      cron.schedule: 0  8  *  *  *
      cron.action: restart
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    group_add:
      - nginx
    volumes:
      - web-certs.mdb:/etc/letsencrypt
      - web-certbot-webroot.mdb:/data/letsencrypt
    links:
      - app-girder
    depends_on:
      - app-girder

volumes:
  app-localassetstore.mdb:
    db-mongodb.mdb:
    external: true
    driver: rancher-nfs
  app-curatedassetstore.mdb:
    db-mongodb.mdb:
    external: true
    driver: rancher-nfs
  db-mongodb.mdb:
    external: true
    driver: rancher-nfs

