version: '2'
services:
  mongodb:
    image: mongo:3.6
    volumes:
        - /mongodb:/data/db

  rabbit:
    image: rabbitmq:latest

  girder_worker:
    image: openchemistry/girder_worker:mdb
    build:
      context: ../../
      dockerfile: devops/docker/girder_worker/Dockerfile
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - rabbit

  girder:
    image: openchemistry/girder:mdb
    build:
      context: ../../
      dockerfile: devops/docker/girder/Dockerfile
    command: -d mongodb://mongodb:27017/girder
    ports:
          - 8081:8080
    volumes:
      - /assetstore:/assetstore
    links:
      - mongodb
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - mongodb

  nginx:
    image: openchemistry/nginx:mdb
    build:
      context: ../../
      dockerfile: devops/docker/nginx/Dockerfile
    ports:
      - 80:80
    links:
      - girder
    depends_on:
      - girder

volumes:
    assetstore:
    mongodb:

