- name: Setting up Girder
  hosts: localhost
  vars:
    required_ansible_version: 2.1.0
  tasks:
    - fail: msg="Playbook requires ansible >= {{required_ansible_version}}"
      when: ansible_version.string|version_compare(required_ansible_version, '<')

    - name: Create Girder mdb user
      girder:
        port: 8080
        user:
          firstName: "mdb"
          lastName: "mdb"
          login: "mdbadmin"
          password: "{{ mdb_password }}"
          email: "mdb@kitware.com"
          admin: yes
        state: present

    - name: Enable MDB plugins
      girder:
        port: 8080
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        plugins:
          - materialsdatabank
        state: present

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/assetstore"
          current: true
        state: present

    - name: Restart the server
      girder:
        port: 8080
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        put:
          path: "system/restart"

    - name: Wait until server restarts
      wait_for:
        port=8080
        delay=5
