- name: Setting up Girder
  hosts: localhost
  vars:
    required_ansible_version: 2.1.0
  tasks:
    - fail: msg="Playbook requires ansible >= {{required_ansible_version}}"
      when: ansible_version.string|version_compare(required_ansible_version, '<')

    - name: Set some facts
      set_fact:
        girder_host: "{{girder_host|default('localhost')}}"
        girder_port: "{{girder_port|default(8080)}}"
    - name:
      debug: msg="{{girder_host}}"
    - name: Create Girder mdb user
      girder:
        host: "{{girder_host}}"
        port: "{{girder_port}}"
        user:
          firstName: "mdb"
          lastName: "mdb"
          login: "mdbadmin"
          password: "{{ mdb_password }}"
          email: "mdb@kitware.com"
          admin: yes
        state: present

    - name: Enable MDB plugins
      girder:
        host: "{{girder_host}}"
        port: "{{girder_port}}"
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        plugins:
          - materialsdatabank
        state: present

    - name: Create filesystem assetstore
      girder:
        host: "{{girder_host}}"
        port: "{{girder_port}}"
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/assetstore"
          current: true
        state: present

    - name: Restart the server
      girder:
        host: "{{girder_host}}"
        port: "{{girder_port}}"
        username: "mdbadmin"
        password: "{{ mdb_password }}"
        put:
          path: "system/restart"

    - name: Wait until server restarts
      wait_for:
        host="{{girder_host}}"
        port="{{girder_port}}"
        delay=5
